### ISSUE TITLE
Inference questions

### ISSUE THREAD

**Issue by heorhiikalaichev** [openface-io/acne-lds#1]
Hi!

I'm wondering if you are going to share weights and inference script!!!
Thank you

**Comment by alxndrkalinin** [comment]
Thanks for your interest in our work. We will share model weights and prediction code in the next few weeks.

**Comment by EaRu723** [comment]
Following this thread, also interested in weights I'd be able to use locally

**Comment by alxndrkalinin** [comment]
Pre-trained weights are now [available](https://github.com/openface-io/acne-lds?tab=readme-ov-file#quick-links)
